### PR TITLE
Change ID to v2ray-plugin with back compatibility

### LINKED ISSUE #18: Change plugin id from 'v2ray' to 'v2ray-plugin' for consistency
#13 was closed without any comments so I opened another one.

### PR DESCRIPTION
**Pull request by Mygod**
Fixes #18.

See also https://github.com/shadowsocks/shadowsocks-android/pull/2431.

### CODE REVIEW

**Comment by CzBiX** [comment]
应该用 `v2ray-plugin` 当 id，`v2ray` 当 alias？
不然导出的时候还会是 `v2ray`，没法在其他平台使用了。

**Comment by Mygod** [comment]
shadowsocks-android will respect whichever is imported when exporting.

**Comment by CzBiX** [comment]
我是指用户在手机上编辑配置文件，选择了 `v2ray` 插件，然后导出的情况。

**Review by madeye — APPROVED** [review]

**Comment by Mygod** [comment]
@CzBiX Accepted considering the file naming in shadowsocks/v2ray-plugin.

**Comment by Mygod** [comment]
@madeye Testing this change shouldn't require an update for plugin library. :)

**Comment by madeye** [comment]
The new plugin has been released.. 

I guess the problem is the go version. I also updated the v2ray-plugin, which depends on go 1.13.

**Comment by Mygod** [comment]
We should release the main app first otherwise the alias thing will not be migrated smoothly.

**Comment by madeye** [comment]
Sure, I'll release the shadowsocks app first.

**Comment by Mygod** [comment]
Done fixing some issues in v5.0.3 now.

**Pull request merged**
