### PR TITLE
Add /metadata/ for F-Droid

### PR DESCRIPTION
**Pull request by mahc9kez**
Hi I just successfully build this app with [fdroid](https://gitlab.com/fdroid/fdroidserver) software on my machine.

`/metadata/` is used for generate metadata on F-Droid, showing app info/description/summary on F-Droid website and client. Most of these info are get from [Google Play](https://play.google.com/store/apps/details?id=com.github.shadowsocks.plugin.v2ray), these two screenshot are taken by me because I can't download screenshot in high resolution from Google Play.

More about F-Droid metadata:
1. [F-Droid doc](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository)
2. [fastlane supply](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots)
3. [Triple-T Gradle Play Publisher](https://github.com/Triple-T/gradle-play-publisher#play-store-metadata)

> metadata/com.github.shadowsocks.plugin.v2ray.yml

This is the build metadata I wrote and partly tested and should works for building v1.3.1. but saving this in `/metadata/` is not necessary.

Once F-Droid build it successfully, it could check updates automatically, new tag `^v*` will trigger the update and automatically build the new version. So almostly nothing you need to change for further development. But it would be better if you add changelog (`metadata/<locale>/changelogs/<versioncode>.txt`) before each tag release.

btw recently am also [trying to bring my fork of shadowsocks-android to F-Droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/6093)

### CODE REVIEW

**Comment by dimqua** [comment]
Thanks! I hope your MR will be merged, and since this plugin is quite important (and fully FOSS), it'd nice to have it added as well.

**Comment by mahc9kez** [comment]
I just noticed it's possible specific output path.
`output: glob/to/output.apk`
https://f-droid.org/en/docs/Build_Metadata_Reference/

I will try it later and report later. maybe it's not necessary to touch gradle config, just add `/metadata/`

**Review by Mygod — APPROVED** [review]
Lgtm if it works

**Comment by mahc9kez** [comment]
It works by specific output path, so no changes need to applied to current codes, only `/metadata/` need to be added (not essential for building).

I have opened a merge request on fdroiddata for building V2ray Plugin on F-Droid.
https://gitlab.com/fdroid/fdroiddata/merge_requests/6105

**Pull request merged**
