### PR TITLE
Refine Android plugin

### PR DESCRIPTION
**Pull request by Mygod**
@madeye Have we ever discussed how to handle `;` and `\n` in plugin arguments?

### CODE REVIEW

**Comment by madeye** [comment]
Nope, maybe just escape them with `\`.

**Comment by Mygod** [comment]
Write permissions? 😅

**Comment by madeye** [comment]
Let me check...

**Comment by Mygod** [comment]
Permissions seem fine now. Great.

Actually I don't think we allow crazy characters like `\0\n` etc. in options. Let's just say anything that uses that should probably consider an additional configuration file instead?

UPDATE: Fixed via https://github.com/shadowsocks/shadowsocks-android/pull/2072/commits/9f037d2afe96531d02ec23574429dfb523622fd7.

**Pull request merged**
